basePath: /v1
definitions:
  helper.BaseResponse:
    properties:
      data: {}
      error: {}
      messages:
        type: string
      meta:
        $ref: '#/definitions/helper.Meta'
    type: object
  helper.Meta:
    properties:
      page:
        type: integer
      total_data:
        type: integer
      total_page:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: taufikjanuar35@gmail.com
    name: Taufik Januar
  description: Revamped URL Shortener API
  license:
    name: MIT
  title: Singkatin Revamp API
  version: "1.0"
paths:
  /health-check:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.BaseResponse'
      summary: Checking Health Services
      tags:
      - Health Check
schemes:
- http
swagger: "2.0"
