basePath: /v1
definitions:
  helper.BaseResponse:
    properties:
      data: {}
      error: {}
      messages:
        type: string
      meta:
        $ref: '#/definitions/helper.Meta'
    type: object
  helper.Meta:
    properties:
      page:
        type: integer
      total_data:
        type: integer
      total_page:
        type: integer
    type: object
  model.ForgotPasswordRequest:
    properties:
      email:
        type: string
    type: object
  model.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  model.RegisterRequest:
    properties:
      email:
        type: string
      fullname:
        type: string
      password:
        type: string
    type: object
  model.ResetPasswordRequest:
    properties:
      new_password:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: taufikjanuar35@gmail.com
    name: Taufik Januar
  description: Revamped URL Shortener API - Auth Services
  license:
    name: MIT
  title: Singkatin Revamp API
  version: "1.0"
paths:
  /forgot-password:
    post:
      consumes:
      - application/json
      parameters:
      - description: forgot password user
        in: body
        name: forgotPassword
        required: true
        schema:
          $ref: '#/definitions/model.ForgotPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.BaseResponse'
      summary: Forgot Password Users
      tags:
      - Auth
  /forgot-password/verify:
    get:
      consumes:
      - application/json
      parameters:
      - description: Code Verification
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.BaseResponse'
      summary: Verify Forgot Password Users
      tags:
      - Auth
  /health-check:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.BaseResponse'
      summary: Checking Health Services
      tags:
      - Health Check
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: login user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.BaseResponse'
      summary: Login users
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - description: register user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.BaseResponse'
      summary: Register users
      tags:
      - Auth
  /register/verify:
    get:
      consumes:
      - application/json
      parameters:
      - description: Code Verification
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.BaseResponse'
      summary: Verify Register Users
      tags:
      - Auth
  /reset-password:
    put:
      consumes:
      - application/json
      parameters:
      - description: Code Verification
        in: query
        name: code
        required: true
        type: string
      - description: reset password user
        in: body
        name: forgotPassword
        required: true
        schema:
          $ref: '#/definitions/model.ResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.BaseResponse'
      summary: Reset Password Users
      tags:
      - Auth
schemes:
- http
swagger: "2.0"
