basePath: /v1
definitions:
  helper.BaseResponse:
    properties:
      data: {}
      error: {}
      messages:
        type: string
      meta:
        $ref: '#/definitions/helper.Meta'
    type: object
  helper.Meta:
    properties:
      page:
        type: integer
      total_data:
        type: integer
      total_page:
        type: integer
    type: object
  model.EditProfileRequest:
    properties:
      full_name:
        type: string
    type: object
  model.ShortUserRequest:
    properties:
      full_url:
        type: string
    type: object
host: localhost:8082
info:
  contact:
    email: taufikjanuar35@gmail.com
    name: Taufik Januar
  description: Revamped URL Shortener API - User Services
  license:
    name: MIT
  title: Singkatin Revamp API
  version: "1.0"
paths:
  /dashboard:
    get:
      consumes:
      - application/json
      parameters:
      - description: Authorization Bearer <Place Access Token Here>
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.BaseResponse'
      summary: Get Dashboard
      tags:
      - User
  /health-check:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.BaseResponse'
      summary: Checking Health Services
      tags:
      - Health Check
  /me:
    get:
      consumes:
      - application/json
      parameters:
      - description: Authorization Bearer <Place Access Token Here>
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.BaseResponse'
      summary: Get Profiles
      tags:
      - User
  /me/edit:
    put:
      consumes:
      - application/json
      parameters:
      - description: Authorization Bearer <Place Access Token Here>
        in: header
        name: Authorization
        required: true
        type: string
      - description: generate short user
        in: body
        name: profile
        required: true
        schema:
          $ref: '#/definitions/model.EditProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.BaseResponse'
      summary: Update Users Profile
      tags:
      - User
  /short/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: id short urls
        in: path
        name: id
        required: true
        type: string
      - description: Authorization Bearer <Place Access Token Here>
        in: header
        name: Authorization
        required: true
        type: string
      - description: update short user
        in: body
        name: short
        required: true
        schema:
          $ref: '#/definitions/model.ShortUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.BaseResponse'
      summary: Update Users Short URL
      tags:
      - User
  /short/generate:
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization Bearer <Place Access Token Here>
        in: header
        name: Authorization
        required: true
        type: string
      - description: generate short user
        in: body
        name: short
        required: true
        schema:
          $ref: '#/definitions/model.ShortUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.BaseResponse'
      summary: Generate Users Short URL
      tags:
      - User
  /upload/avatar:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Authorization Bearer <Place Access Token Here>
        in: header
        name: Authorization
        required: true
        type: string
      - description: file avatar
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.BaseResponse'
      summary: Upload Users Avatar
      tags:
      - User
schemes:
- http
swagger: "2.0"
