basePath: /v1
definitions:
  helper.BaseResponse:
    properties:
      data: {}
      error: {}
      messages:
        type: string
      meta:
        $ref: '#/definitions/helper.Meta'
    type: object
  helper.Meta:
    properties:
      page:
        type: integer
      total_data:
        type: integer
      total_page:
        type: integer
    type: object
host: localhost:8081
info:
  contact:
    email: taufikjanuar35@gmail.com
    name: Taufik Januar
  description: Revamped URL Shortener API - Shortener Services
  license:
    name: MIT
  title: Singkatin Revamp API
  version: "1.0"
paths:
  /{short_url}:
    get:
      consumes:
      - application/json
      parameters:
      - description: short urls
        in: path
        name: short_url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "301":
          description: Moved Permanently
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.BaseResponse'
      summary: Click Shorteners URL
      tags:
      - Shortener
  /health-check:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.BaseResponse'
      summary: Checking Health Services
      tags:
      - Health Check
schemes:
- http
swagger: "2.0"
