// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: api/v1/proto/shortener/shortener.proto

package shortenerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Shortener struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullUrl  string `protobuf:"bytes,2,opt,name=full_url,json=fullUrl,proto3" json:"full_url,omitempty"`
	ShortUrl string `protobuf:"bytes,3,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	Visited  int64  `protobuf:"varint,4,opt,name=visited,proto3" json:"visited,omitempty"`
}

func (x *Shortener) Reset() {
	*x = Shortener{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Shortener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shortener) ProtoMessage() {}

func (x *Shortener) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shortener.ProtoReflect.Descriptor instead.
func (*Shortener) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_shortener_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *Shortener) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shortener) GetFullUrl() string {
	if x != nil {
		return x.FullUrl
	}
	return ""
}

func (x *Shortener) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *Shortener) GetVisited() int64 {
	if x != nil {
		return x.Visited
	}
	return 0
}

type ListShortenerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ListShortenerRequest) Reset() {
	*x = ListShortenerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListShortenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShortenerRequest) ProtoMessage() {}

func (x *ListShortenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShortenerRequest.ProtoReflect.Descriptor instead.
func (*ListShortenerRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_shortener_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ListShortenerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListShortenerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shorteners []*Shortener `protobuf:"bytes,1,rep,name=shorteners,proto3" json:"shorteners,omitempty"`
}

func (x *ListShortenerResponse) Reset() {
	*x = ListShortenerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListShortenerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShortenerResponse) ProtoMessage() {}

func (x *ListShortenerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShortenerResponse.ProtoReflect.Descriptor instead.
func (*ListShortenerResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_shortener_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *ListShortenerResponse) GetShorteners() []*Shortener {
	if x != nil {
		return x.Shorteners
	}
	return nil
}

type CreateShortenerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FullUrl  string `protobuf:"bytes,2,opt,name=full_url,json=fullUrl,proto3" json:"full_url,omitempty"`
	ShortUrl string `protobuf:"bytes,3,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *CreateShortenerMessage) Reset() {
	*x = CreateShortenerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShortenerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortenerMessage) ProtoMessage() {}

func (x *CreateShortenerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortenerMessage.ProtoReflect.Descriptor instead.
func (*CreateShortenerMessage) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_shortener_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *CreateShortenerMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateShortenerMessage) GetFullUrl() string {
	if x != nil {
		return x.FullUrl
	}
	return ""
}

func (x *CreateShortenerMessage) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type UpdateVisitorCountMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *UpdateVisitorCountMessage) Reset() {
	*x = UpdateVisitorCountMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVisitorCountMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVisitorCountMessage) ProtoMessage() {}

func (x *UpdateVisitorCountMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVisitorCountMessage.ProtoReflect.Descriptor instead.
func (*UpdateVisitorCountMessage) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_shortener_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateVisitorCountMessage) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type UpdateShortenerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullUrl string `protobuf:"bytes,2,opt,name=full_url,json=fullUrl,proto3" json:"full_url,omitempty"`
}

func (x *UpdateShortenerMessage) Reset() {
	*x = UpdateShortenerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateShortenerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShortenerMessage) ProtoMessage() {}

func (x *UpdateShortenerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShortenerMessage.ProtoReflect.Descriptor instead.
func (*UpdateShortenerMessage) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_shortener_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateShortenerMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateShortenerMessage) GetFullUrl() string {
	if x != nil {
		return x.FullUrl
	}
	return ""
}

type DeleteShortenerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteShortenerMessage) Reset() {
	*x = DeleteShortenerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteShortenerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShortenerMessage) ProtoMessage() {}

func (x *DeleteShortenerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_shortener_shortener_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShortenerMessage.ProtoReflect.Descriptor instead.
func (*DeleteShortenerMessage) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_shortener_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteShortenerMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_api_v1_proto_shortener_shortener_proto protoreflect.FileDescriptor

var file_api_v1_proto_shortener_shortener_proto_rawDesc = []byte{
	0x0a, 0x26, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72,
	0x22, 0x6d, 0x0a, 0x09, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x66, 0x75, 0x6c, 0x6c, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x73, 0x69, 0x74, 0x65, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x69, 0x73, 0x69, 0x74, 0x65, 0x64, 0x22,
	0x2f, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x5a, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72,
	0x52, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x73, 0x22, 0x69, 0x0a, 0x16,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x66, 0x75, 0x6c, 0x6c, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x38, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x56, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72,
	0x6c, 0x22, 0x43, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x6e, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x66,
	0x75, 0x6c, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66,
	0x75, 0x6c, 0x6c, 0x55, 0x72, 0x6c, 0x22, 0x28, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x32, 0x8b, 0x01, 0x0a, 0x10, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x77, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x2c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x55,
	0x5a, 0x53, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x50, 0x69, 0x63,
	0x6b, 0x48, 0x44, 0x2f, 0x73, 0x69, 0x6e, 0x67, 0x6b, 0x61, 0x74, 0x69, 0x6e, 0x2d, 0x72, 0x65,
	0x76, 0x61, 0x6d, 0x70, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x3b, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_proto_shortener_shortener_proto_rawDescOnce sync.Once
	file_api_v1_proto_shortener_shortener_proto_rawDescData = file_api_v1_proto_shortener_shortener_proto_rawDesc
)

func file_api_v1_proto_shortener_shortener_proto_rawDescGZIP() []byte {
	file_api_v1_proto_shortener_shortener_proto_rawDescOnce.Do(func() {
		file_api_v1_proto_shortener_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_proto_shortener_shortener_proto_rawDescData)
	})
	return file_api_v1_proto_shortener_shortener_proto_rawDescData
}

var file_api_v1_proto_shortener_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_v1_proto_shortener_shortener_proto_goTypes = []interface{}{
	(*Shortener)(nil),                 // 0: api.v1.proto.shortener.Shortener
	(*ListShortenerRequest)(nil),      // 1: api.v1.proto.shortener.ListShortenerRequest
	(*ListShortenerResponse)(nil),     // 2: api.v1.proto.shortener.ListShortenerResponse
	(*CreateShortenerMessage)(nil),    // 3: api.v1.proto.shortener.CreateShortenerMessage
	(*UpdateVisitorCountMessage)(nil), // 4: api.v1.proto.shortener.UpdateVisitorCountMessage
	(*UpdateShortenerMessage)(nil),    // 5: api.v1.proto.shortener.UpdateShortenerMessage
	(*DeleteShortenerMessage)(nil),    // 6: api.v1.proto.shortener.DeleteShortenerMessage
}
var file_api_v1_proto_shortener_shortener_proto_depIdxs = []int32{
	0, // 0: api.v1.proto.shortener.ListShortenerResponse.shorteners:type_name -> api.v1.proto.shortener.Shortener
	1, // 1: api.v1.proto.shortener.ShortenerService.GetListShortenerByUserID:input_type -> api.v1.proto.shortener.ListShortenerRequest
	2, // 2: api.v1.proto.shortener.ShortenerService.GetListShortenerByUserID:output_type -> api.v1.proto.shortener.ListShortenerResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_proto_shortener_shortener_proto_init() }
func file_api_v1_proto_shortener_shortener_proto_init() {
	if File_api_v1_proto_shortener_shortener_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_proto_shortener_shortener_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Shortener); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_shortener_shortener_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListShortenerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_shortener_shortener_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListShortenerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_shortener_shortener_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShortenerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_shortener_shortener_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVisitorCountMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_shortener_shortener_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateShortenerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_proto_shortener_shortener_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteShortenerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_proto_shortener_shortener_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_proto_shortener_shortener_proto_goTypes,
		DependencyIndexes: file_api_v1_proto_shortener_shortener_proto_depIdxs,
		MessageInfos:      file_api_v1_proto_shortener_shortener_proto_msgTypes,
	}.Build()
	File_api_v1_proto_shortener_shortener_proto = out.File
	file_api_v1_proto_shortener_shortener_proto_rawDesc = nil
	file_api_v1_proto_shortener_shortener_proto_goTypes = nil
	file_api_v1_proto_shortener_shortener_proto_depIdxs = nil
}
